export const getChatStyle = (isChatAreaVisible, isTabletOrMobile) => {
  return {
    container: {
      display: "flex",
      flexDirection: isTabletOrMobile ? "column" : "row",
      justifyContent: "start",
      alignItems: "flex-start",
      margin: "20px",
      fontFamily: "'Arial', sans-serif",
      color: "#333",
      height: "80vh",
    },
    userList: {
      display: isTabletOrMobile ? (isChatAreaVisible ? "none" : "") : "",
      flex: 1,
      borderRadius: "5px",
      padding: "10px",
      overflowY: "scroll",
      height: "80vh",
      maxWidth: isTabletOrMobile ? "" : "20vw",
      minWidth: isTabletOrMobile ? "80vw" : "",
      marginRight: "20px",
      backgroundColor: "rgba(240, 240, 240, 0.6)",
      textAlign: "left",
    },
    chatArea: {
      paddingTop: "10px",
      flex: 2,
      display: isChatAreaVisible ? "flex" : "none",
      flexDirection: "column",
      borderRadius: "5px",
      justifyContent: "space-between",
      height: "81.5vh",
      width: isTabletOrMobile ? "" : "100vw",
      minWidth: isTabletOrMobile ? "85vw" : "",
      backgroundColor: "rgba(255, 255, 255, 0.5)",
      transition: "transform 0.3s ease-in-out",
      transform: isChatAreaVisible ? "translateY(0)" : "translateY(100%)",
    },
    messageHistory: {
      padding: "10px",
      overflowY: "scroll",
      flexGrow: "1",
    },
    form: {
      display: "flex",
      marginTop: "10px",
    },
    input: {
      flexGrow: "1",
      padding: "10px",
      margin: "0 10px 0 0",
      borderRadius: "5px",
      border: "1px solid #ccc",
    },
    button: {
      padding: "10px 20px",
      borderRadius: "5px",
      border: "none",
      backgroundColor: "#1a1a1a",
      color: "white",
      cursor: "pointer",
    },
    closeButton: {
      display: "block",
      alignSelf: "flex-end",
      cursor: "pointer",
      padding: "10px",
      margin: "auto",
      background: "rgba(222, 49, 61, 0.946)",
      color: "#fcf9f9",
      borderRadius: "5px",
      border: "none",
      fontWeight: "bold",
    },
    message: {
      padding: "5px",
      margin: "5px 0",
      borderRadius: "5px",
      backgroundColor: "#f2f2f2",
      wordWrap: "break-word",
      whiteSpace: "pre-line",
    },
    sentMessage: {
      color: "rgba(200, 200, 200, 1)",
      textAlign: "right",
      backgroundColor: "rgba(0, 10, 255, 0.5)",
      width: "100%",
    },
    receivedMessage: {
      color: "rgba(0, 0, 0, 0.8)",
      textAlign: "left",
      backgroundColor: "rgba(0, 255, 80, 0.3)",
    },
    userButton: {
      display: "block",
      width: "100%",
      minWidth: "100px",
      padding: "10px",
      margin: "5px 0",
      backgroundColor: "#ffffff",
      opacity: 0.5,
      color: "black",
      textAlign: "left",
      border: "none",
      borderRadius: "5px",
      cursor: "pointer",
      textAlign: "center",
    },
    selectedButton: {
      backgroundColor: "rgba(10, 139, 71, 0.946)",
      color: "white",
      margin: "5px 0",
    },
  };
};
