name: Build and deploy Node.js app to Azure Web App - Onlinechat-Server

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          cd onlinechat-server
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip the build output
        run: |
          Compress-Archive -Path onlinechat-server -DestinationPath onlinechat-server.zip

      - name: Upload zipped artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: onlinechat-server.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download zipped artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'Onlinechat-Server'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_05AFCD70A6DE4FF599723BFF70EED6C4 }}
          package: onlinechat-server.zip
